### ISSUE TITLE
Monal 3.1 and Old Style SSL

### ISSUE THREAD

**Issue by vpciii** [anurodhp/Monal#138]
I wasn't sure if I should start a new issue, but I can't connect with the latest client 3.1.  We use and openfire server and old style SSL.

The previous version connected fine.  The new version has an SSL issue.  This is from the openfire admin log when attempting to connect with 3.1:

2018.11.30 11:41:09 org.jivesoftware.openfire.nio.ConnectionHandler - Closing connection due to exception in session: (0x000000EB: nio socket, server, /72.23.141.172:44850 => /10.91.92.27:5223) 
javax.net.ssl.SSLHandshakeException: SSL handshake failed. 
at org.apache.mina.filter.ssl.SslFilter.messageReceived(SslFilter.java:487) 
at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417) 
at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47) 
at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765) 
at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:74) 
at org.apache.mina.core.session.IoEvent.run(IoEvent.java:63) 
at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTask(OrderedThreadPoolExecutor.java:769) 
at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTasks(OrderedThreadPoolExecutor.java:761) 
at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.run(OrderedThreadPoolExecutor.java:703) 
at java.lang.Thread.run(Thread.java:748) 
Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection? 
at sun.security.ssl.EngineInputRecord.bytesInCompletePacket(EngineInputRecord.java:171) 
at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:849) 
at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:762) 
at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) 
at org.apache.mina.filter.ssl.SslHandler.unwrap(SslHandler.java:728) 
at org.apache.mina.filter.ssl.SslHandler.unwrapHandshake(SslHandler.java:666) 
at org.apache.mina.filter.ssl.SslHandler.handshake(SslHandler.java:552) 
at org.apache.mina.filter.ssl.SslHandler.messageReceived(SslHandler.java:351) 
at org.apache.mina.filter.ssl.SslFilter.messageReceived(SslFilter.java:468) 
... 9 more 

I was thinking about getting the source and trying to figure out what the issue is unless you already have a fix in place.

**Comment by anurodhp** [comment]
im installing open fire on a vm to test this

**Comment by anurodhp** [comment]
Quick check , are you ssl certs valid? Are they self signed?

**Comment by vpciii** [comment]
The cert is valid not self signed.  From rapidssl.

**Comment by anurodhp** [comment]
I believe this is fixed now. I have made the beta available online so you can verify this has been resolved. 
https://testflight.apple.com/join/RjIlyvqa

**Comment by Echolon** [comment]
@vpciii  can this be closed with the current version?

**Comment by vpciii** [comment]
Yes it can.

On Dec 26, 2019, at 14:58, Echolon <notifications@github.com> wrote:

@vpciii <https://github.com/vpciii> can this be closed with the current version?
